# ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: myapp
    type: back-end
